# ----------------------------
# Book Metadata
# ----------------------------
title: "Data Sciences and Spikes"
author: "Fabien Campillo"
execute:
  execute_notebooks: auto
logo: "pics/logo_title.png"
copyright: "This book is distributed under CC BY-NC-SA 4.0 (Creative Commons Attribution-NonCommercial-ShareAlike)"

# ----------------------------
# Repository / GitHub buttons
# ----------------------------
repository:
  url: "https://github.com/fabien-campillo/data-science-spikes"
  branch: main
  path_to_book: ""

# ----------------------------
# HTML Configuration
# ----------------------------
html:
  favicon: pics/favicon.ico
  use_repository_button: true
  use_download_button: true
  extra_navbar: |
    <hr>
    <a href="Spikes-Data-Sciences.pdf" target="_blank">📄 Download PDF</a>

# ----------------------------
# Exclude patterns
# ----------------------------
exclude_patterns:
  - .virtual_documents/*

# ----------------------------
# LaTeX / PDF Configuration
# les "  latex_elements:" ne marchent pas
# ----------------------------
latex:
  latex_engine: xelatex
  latex_documents:
    targetname: "Spikes-Data-Sciences.tex"
