title: "Data Science des Spikes"
author: "Fabien Campillo"
execute:
  execute_notebooks: auto
logo: "pics/logo.png"
html:
  favicon: pics/favicon.ico
copyright: 'Contenu sous <a href="https://creativecommons.org/licenses/by/4.0/">licence CC-BY 4.0</a>.'