title: "Spikes Data Sciences"
author: "Fabien Campillo"
execute:
  execute_notebooks: auto
logo: "pics/logo.png"
html:
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true
  toc_depth: 3
  favicon: pics/favicon.ico
  extra_head: |
    <link rel="apple-touch-icon" sizes="200×208" href="_static/apple-touch-icon.png">
copyright: "This book is distributed under CC BY-NC-SA 4.0 (Creative Commons Attribution-NonCommercial-ShareAlike)"
