title: "Spikes Data Sciences"
author: "Fabien Campillo"
execute:
  execute_notebooks: auto
logo: "pics/logo_title.png"
html:
  favicon: pics/favicon.ico
  extra_head: |
    <link rel="apple-touch-icon" sizes="200×208" href="_static/apple-touch-icon.png">
copyright: "This book is distributed under CC BY-NC-SA 4.0 (Creative Commons Attribution-NonCommercial-ShareAlike)"
latex:
  latex_engine: xelatex
html:
  use_repository_button: true
  use_download_button: true
  extra_navbar: |
    <a href="spikes-data-sciences.pdf" target="_blank">📄 Download PDF</a>