#######################################################################################
# Book settings
title: "Data Sciences and Spikes"
author: "Fabien Campillo"
execute:
  execute_notebooks: auto
logo: "pics/logo_title.png"
copyright: "This book is distributed under CC BY-NC-SA 4.0 (Creative Commons Attribution-NonCommercial-ShareAlike)"

#######################################################################################
# Repository settings
repository:
  url: "https://github.com/fabien-campillo/data-science-spikes"
  branch: main
  path_to_book: ""

#######################################################################################
# HTML-specific settings
html:
  favicon: pics/favicon.ico
  use_repository_button: true
  use_download_button: true
  extra_navbar: |
    <hr>
    <a href="Spikes-Data-Sciences.pdf" target="_blank">📄 Download PDF</a>

#######################################################################################
# Exclude patterns
exclude_patterns:
  - .virtual_documents/*

#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine: lualatex
  latex_documents:
    targetname: "Spikes-Data-Sciences.tex"
  latex_elements:
    preamble: |
      \usepackage{emoji}       % use the LaTeX emoji package
      \setmainfont{FreeSerif}  % main font
     
#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:
    - dollarmath
    - colon_fence

#sphinx:
#  config:
#    latex_elements:
#      preamble: |
#        \usepackage{emoji}       % use the LaTeX emoji package
#        \setmainfont{FreeSerif}  % main font
#       fontpkg: |
#        \setmainfont{FreeSerif}
#        \newfontfamily\emoji{Noto Color Emoji}
#        \newfontfamily\emoji{NotoEmoji-Regular.ttf}
#    fc-list | grep "FreeSerif"
#    fc-list | grep "Noto Color Emoji"