# ----------------------------
# Book Metadata
# ----------------------------
title: "Data Sciences and Spikes"
author: "Fabien Campillo"
execute:
  execute_notebooks: auto
logo: "pics/logo_title.png"
copyright: "This book is distributed under CC BY-NC-SA 4.0 (Creative Commons Attribution-NonCommercial-ShareAlike)"

# ----------------------------
# Repository / GitHub buttons
# ----------------------------
repository:
  url: "https://github.com/yourusername/data-science-spikes"
  branch: main
  path_to_book: ""

# ----------------------------
# HTML Configuration
# ----------------------------
html:
  favicon: pics/favicon.ico
  use_repository_button: true
  use_download_button: true
  extra_navbar: |
    <hr>
    <a href="Spikes-Data-Sciences.pdf" target="_blank">📄 Download PDF</a>

# ----------------------------
# Exclude patterns
# ----------------------------
exclude_patterns:
  - .virtual_documents/*

# ----------------------------
# LaTeX / PDF Configuration
# ----------------------------
latex:
  latex_engine: xelatex
  latex_documents:
    targetname: "Spikes-Data-Sciences.tex"
  latex_elements:
    # Packages
    preamble: |
      \usepackage{graphicx}  % needed for including images
    # Custom title page
    maketitle: |
      \begin{titlepage}
        \centering
        \vspace*{2cm}
        \includegraphics[width=0.4\textwidth]{pics/Spikes-Data-Sciences.pdf} % PDF logo for LaTeX
        \vspace{2cm}
        {\Huge \textbf{\@title}} \\[1cm]
        {\Large \@author} \\[1cm]
        \@date
      \end{titlepage}
      
# ----------------------------
# sphinx Configuration
# ----------------------------

sphinx:
  config:
    latex_elements:
      preamble: |
        \usepackage{xcolor}
        \usepackage{tcolorbox}
        % Define environments for callouts
        \newtcolorbox{noteBox}{colback=blue!10!white,colframe=blue!50!black,title=Note}
        \newtcolorbox{tipBox}{colback=green!10!white,colframe=green!50!black,title=Tip}
        \newtcolorbox{warningBox}{colback=yellow!10!white,colframe=orange!50!black,title=Warning}
        \newtcolorbox{importantBox}{colback=red!10!white,colframe=red!50!black,title=Important}