title: "Data Science des Spikes"
author: "Fabien Campillo"
execute:
  execute_notebooks: auto
logo: "pics/logo.png"
html:
  favicon: pics/favicon.ico
copyright: "Ce livre est distribué sous licence CC-BY 4.0 (Creative Commons Attribution)."
