title: "Spikes Data Sciences"
author: "Fabien Campillo"
execute:
  execute_notebooks: auto
logo: "pics/logo.png"
html:
  favicon: pics/favicon.ico
  extra_head: |
    <link rel="apple-touch-icon" sizes="200×208" href="_static/apple-touch-icon.png">
copyright: "This book is distributed under a CC-BY 4.0 license (Creative Commons Attribution)."
