#######################################################################################
# Book settings
title: "Data Sciences and Spikes"
author: "Fabien Campillo"
execute:
  execute_notebooks: auto
logo: "pics/logo_title.png"
copyright: "This book is distributed under CC BY-NC-SA 4.0 (Creative Commons Attribution-NonCommercial-ShareAlike)"

#######################################################################################
# Repository settings
repository:
  url: "https://github.com/fabien-campillo/data-science-spikes"
  branch: main
  path_to_book: ""

#######################################################################################
# HTML-specific settings
html:
  favicon: pics/favicon.ico
  use_repository_button: true
  use_download_button: true
  # restart numbering between parts (not working for PDF)
  use_multitoc_numbering: false
#  extra_navbar: |  # FAILED
#    <div>
#      your html
#    </div>      
#  extra_footer: |  # pour mettrer qqchose ds le footer de toutes les pages TESTED
#    <div>
#      your html
#    </div>

#######################################################################################
# Exclude patterns
exclude_patterns:
  - .virtual_documents/*

#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine: pdflatex
  latex_documents:
    targetname: "Spikes-Data-Sciences.tex"

#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:
    - dollarmath
    - colon_fence

sphinx:
  config:
    latex_elements:
      papersize: a4paper     
  extra_extensions:
    - myst_nb

# MyST Markdown extensions
myst_enable_extensions:
  - footnote          # enables ^[...] sidenotes
  - deflist           # optional: definition lists
  - html_admonition   # optional: note/admonition support
  - html_image        # optional: HTML <img> support
  - colon_fence       # optional: ::: fenced blocks