title: "Data Sciences and Spikes"
author: "Fabien Campillo"
execute:
  execute_notebooks: auto
logo: "pics/logo_title.png"
copyright: "This book is distributed under CC BY-NC-SA 4.0 (Creative Commons Attribution-NonCommercial-ShareAlike)"
latex:
  latex_engine: xelatex
  latex_documents:
    targetname: "Spikes-Data-Sciences.tex"
  latex_elements:
    preamble: |
      \usepackage{graphicx}
      \usepackage{svg}
      \renewcommand{\maketitle}{
        \begin{titlepage}
          \centering
          \vspace*{2cm}
          \includesvg[width=0.4\textwidth]{_static/pics/logo_data_science_spikes.svg} % or \includegraphics for PNG
          \vspace{2cm}
          {\Huge \textbf{\@title}} \\[1cm]
          {\Large \@author} \\[1cm]
          \@date
        \end{titlepage}
      }
repository:
  url: "https://github.com/yourusername/data-science-spikes"
  branch: main
  path_to_book: ""
html:
  favicon: pics/favicon.ico
  use_repository_button: true
  use_download_button: true
  extra_navbar: |
    <hr>
    <a href="spikes-data-sciences.pdf" target="_blank">📄 Download PDF</a>
exclude_patterns:
  - .virtual_documents/*