title: "Spikes Data Sciences"
author: "Fabien Campillo"
execute:
  execute_notebooks: auto
logo: "pics/logo_title.png"
html:
  favicon: pics/favicon.ico
  extra_head: |
    <link rel="apple-touch-icon" sizes="200×208" href="_static/apple-touch-icon.png">
copyright: "This book is distributed under CC BY-NC-SA 4.0 (Creative Commons Attribution-NonCommercial-ShareAlike)"
latex:
  latex_engine: xelatex

# ------------------------
# MyST numbering for Markdown headings
# ------------------------
myst:
  number_headings: 2   # only number levels 1 (#) and 2 (##)

# ------------------------
# Sphinx / TOC numbering
# ------------------------
sphinx:
  extra_extensions:
    - sphinx.ext.autosectionlabel
  config:
    sectnum_depth: 2     # limit TOC numbering to H1 and H2
